# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bgl <- function(n, iters, lambdaPriorb, lambdaPosta, S, Sigma, Omega, keepLambdas) {
    .Call('_BayesianGLasso_bgl', PACKAGE = 'BayesianGLasso', n, iters, lambdaPriorb, lambdaPosta, S, Sigma, Omega, keepLambdas)
}

bAdgl <- function(n, iters, gammaPriors, gammaPriort, lambdaii, S, Sigma, Omega, priorLogical, priorHyper, keepLambdas) {
    .Call('_BayesianGLasso_bAdgl', PACKAGE = 'BayesianGLasso', n, iters, gammaPriors, gammaPriort, lambdaii, S, Sigma, Omega, priorLogical, priorHyper, keepLambdas)
}

